"""
Django settings for AWS3R project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_%tlzo-kj37uor$*gn^fe%9u=i2z0)7&y-zp-qqe98h%^-=ni$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'educate',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AWS3R.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AWS3R.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ddac_backend',
        'USER': 'DDAC061320',
        'PASSWORD': 'Nice10day',
        'HOST': 'ddacbackend2.cd8eu2k4w9p7.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Update AWS_KEY_ID, SECRET_ACCESS_KEY and SESSION_TOKEN fields everytime 
AWS_ACCESS_KEY_ID = 'ASIAQ3EGU5RWG2YPPWCX'
AWS_SECRET_ACCESS_KEY = 'skT6UtiR2JqKQeESUiW9qTHDMGrg5B8JimUZKOL0'
AWS_SESSION_TOKEN='IQoJb3JpZ2luX2VjEF8aCXVzLXdlc3QtMiJGMEQCIHDsNuaE9VTQ567xSQLndGAwBJUGTgSuuzLu6aEfVWF1AiBO7wdsxW8zItaeB56cQemNfAMIRdfCza9oF6I6fvGPWyq7Agi4//////////8BEAAaDDA1ODI2NDQ0ODEwOCIMrp9JeeUssD+t7oqKKo8CTKwSGYMyrLKA2+O+Iqekr4MzLEhJVHzJsak4IJ57Q7MyVu0Xw8Azv+QX2AL9MGFqyZ3dL4bfSypjgMJVHnNDpzPlExQjgo2oG1wreSghPBRPLXHFP51wNTuPXqHu5pJiVunN9OJZZMgjpkpQq1uJUTRhoWw5CmCGJ7vPSHf/0GODPHM9Y/mzMF66skAvL3kJxDZOZHuZqKqmTvGwxSwmJXUouSQSXrzCRIUJLpRIgWqgfnSKutj9vqzYu99AJty2bk3a8dC+ROPURG3ZLwCUc3uuIvUupMLqKaFSB4+VkHq4LdPKoOgh+7n11QqG4gRkk2s7S4zXh+NtVCeUfOVnwJF63P7B72ehaPvNx5WXLDDa/+GxBjqeAevp9CrvMzhf8A6HdiJGBod+odKyM1Rwe2nz1pgYbZBNcelgIizEZ0P3zPOkLCdgK6YF1mbYaogX79Fr2JLkr08gPPhgiTwSlN8wIqfFQUWalex33qPcVqzesd/sBKPuGgy4GiO7JfCf6eglpQxPe6/3+Tb9WYyOXx8Jgq97t5ta7TvKo3gzhX2pvwAbLPEEvKLpaTJyrpK+Aqb0eciG'
AWS_STORAGE_BUCKET_NAME = 'ddacs3'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERITY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
